### ISSUE TITLE
TypeError: invalid file: PosixPath('wall.log')

### ISSUE THREAD

**Issue by denzilc** [weskerfoot/DeleteFB#75]
I receive the following error 

> TypeError: invalid file: PosixPath('wall.log')

I have used the following command (git clone + run) to tun the script.

> python -m deletefb.deletefb -E 'email@com' -P 'pwd' -U 'https://www.facebook.com/username'

What could this possibly refer to?

**Comment by weskerfoot** [comment]
@denzilc I think it's your python version. Are you using <3.6?

It's tested with 3.6 or greater (see https://github.com/weskerfoot/DeleteFB#how-to-use-it ). If your system python is older than 3.6, then I would recommend either installing 3.6 (if you can) or use something like Pyenv to allow for newer versions of Python 3 alongside the system one.

https://github.com/pyenv/pyenv

I wasn't aware that this interface is not backwards compatible, so maybe I can take a look and see if it's possible to make backwards compatible, but TBH I would rather just support 3.6 or greater at this point, since it's already tied to Python 3 and doesn't support 2.

https://docs.python.org/3/whatsnew/3.6.html#pep-519-adding-a-file-system-path-protocol

**Comment by weskerfoot** [comment]
Hmm actually it looks like it should be easy to fix. Just calling the `str()` constructor on it should work.

**Comment by weskerfoot** [comment]
@denzilc Should be fixed in master now. Please give it another try :)

**Comment by denzilc** [comment]
Thanks, it works : )
